### ISSUE TITLE
Stackoverflow when using groups without defining xjcVersion

### ISSUE THREAD

**Issue by egaga** [bjornvester/xjc-gradle-plugin#23]
If _xjcVersion.set("2.3.3")_ (or 3.0.0) is omitted when using _groups_  to define multiple schema generations, the gradle build fails mysteriously with:

```
java.lang.StackOverflowError
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
        at org.gradle.api.internal.provider.AbstractProperty.getProducer(AbstractProperty.java:178)
(and so on...)
```

**Comment by evantill** [comment]
could we make a PR for this ?
